In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import pandas as pd
import time
import DateTime
from selenium.webdriver.common.keys import Keys

In [2]:
driver = webdriver.Chrome('/Users/koojaehong/Jupyter_notebook/chromedriver')

/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/2578605976.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome('/Users/koojaehong/Jupyter_notebook/chromedriver')

In [3]:
driver.get('https://kbl.or.kr/game/schedule-list')

In [4]:
# 매치박스안의 경기를 선택하는 xpath
def click_match_box():
    driver.find_element(By.XPATH, '//*[@id="container"]/main/div[3]/div/div[2]/div/div/select').click()

In [8]:
click_match_box()

In [9]:
driver.find_element(By.XPATH, '//*[@id="container"]/main/div[3]/div/div[2]/div/div/select/option[1]').click()

In [10]:
# 매치박스안의 경기를 선택하는 xpath
def click_match(game_num):
    driver.find_element(By.XPATH, '//*[@id="container"]/main/div[3]/div/div[2]/div/div/select/option['+str(game_num)+']').click()

In [12]:
click_match(2)

In [13]:
driver.find_element(By.XPATH, '//*[@id="container"]/main/div[3]/div/div[2]/div/div/select').text

'창원LG VS 서울삼성 [창원실내]\n부산KTF VS 울산모비스 [부산사직]\n안양KT&G VS 원주동부 [안양실내]\n서울SK VS 전주KCC [잠실학생실내]'

In [14]:
driver.find_element(By.XPATH, '//*[@id="container"]/main/div[3]/div/div[2]/div/div/select').text.split('\n')

['창원LG VS 서울삼성 [창원실내]',
 '부산KTF VS 울산모비스 [부산사직]',
 '안양KT&G VS 원주동부 [안양실내]',
 '서울SK VS 전주KCC [잠실학생실내]']

In [15]:
# 매치박스안의 경기 수를 파악하는 함수
def match_len():
    match_length = len(driver.find_element(By.XPATH, '//*[@id="container"]/main/div[3]/div/div[2]/div/div/select').text.split('\n'))
    
    return match_length

In [16]:
match_len()

4

In [17]:
driver.find_element(By.XPATH, '//*[@id="container"]/main/div[3]/div/div[1]/span/a[2]/i').click()

In [21]:
def click_next_day():
    driver.find_element(By.XPATH, '//*[@id="container"]/main/div[3]/div/div[1]/span/a[2]/i').click()

In [22]:
click_next_day()

In [23]:
driver.find_element(By.XPATH, '//*[@id="container"]/main/div[3]/div/div[1]/span/span').text

'2006.10.20 (금)'

In [56]:
data_date()[-14]

'2'

In [54]:
data_date()[-5:-1]

'9 (목'

In [24]:
def data_date():
    date = driver.find_element(By.XPATH, '//*[@id="container"]/main/div[3]/div/div[1]/span/span').text
    date_edited = date[:-4]

    return date_edited

In [25]:
data_date()

'2006.10.20'

In [26]:
# 팀 이름을 가져오는 함수(1:홈팀, 2:어웨이팀)
def data_team_name(team_num):
    team_name = driver.find_element(By.XPATH, '//*[@id="container"]/main/div[3]/div/section[1]/div[1]/div['+str(team_num)+']/div[2]').text
    
    return team_name

In [ ]:
//*[@id="container"]/main/div[3]/div/section[1]/div[2]/table/tbody/tr[1]/td[2]
//*[@id="container"]/main/div[3]/div/section[1]/div[2]/table/tbody/tr[1]/td[3]

//*[@id="container"]/main/div[3]/div/section[1]/div[2]/table/tbody/tr[2]/td[2]
//*[@id="container"]/main/div[3]/div/section[1]/div[2]/table/tbody/tr[2]/td[3]

In [27]:
# 쿼터 점수가져오는 함수(tr->1: 홈팀. 2:어웨이팀, td->2~7 : 1~4/연장/토탈)
def data_score(team_num, qt):
    score = driver.find_element(By.XPATH, '//*[@id="container"]/main/div[3]/div/section[1]/div[2]/table/tbody/tr['+str(team_num)+']/td['+str(qt)+']').text
    
    return score

In [28]:
data_score(1, 2)

'18'

In [29]:
# Stat 가져오는 함수(td->1:홈팀 3:어웨이팀, tr->1~14 : 2점슛 성공개수~3점슛 성공률)
def data_stat(team_num, stat_num):
    if team_num==1:
        stat = driver.find_element(By.XPATH, '//*[@id="container"]/main/div[3]/div/section[2]/section[4]/table/tbody/tr['+str(stat_num)+']/td[1]/span[2]').text
    elif team_num==2:
        stat = driver.find_element(By.XPATH, '//*[@id="container"]/main/div[3]/div/section[2]/section[4]/table/tbody/tr['+str(stat_num)+']/td[3]/span[1]').text
    else:
        pass
    
    return stat

In [30]:
data_stat(1,1)

'30'

In [31]:
data_stat(2,1)

'25'

In [30]:
## 동작 관련 함수
# 경기목록을 클릭하는 함수
def click_match_box():
    driver.find_element(By.XPATH, '//*[@id="container"]/main/div[3]/div/div[2]/div/div/select').click()

# 경기목록 안의 경기를 선택하는 함수
def click_match(game_num):
    driver.find_element(By.XPATH, '//*[@id="container"]/main/div[3]/div/div[2]/div/div/select/option['+str(game_num)+']').click()
    
# 매치박스안의 경기 수를 파악하는 함수
def match_len():
    match_length = len(driver.find_element(By.XPATH, '//*[@id="container"]/main/div[3]/div/div[2]/div/div/select').text.split('\n'))
    
    return match_length

# 다음 날짜 버튼을 클릭하는 함수
def click_next_day():
    driver.find_element(By.XPATH, '//*[@id="container"]/main/div[3]/div/div[1]/span/a[2]/i').click()


## 데이터 추출 관련 함수
# 날짜 추출하는 함수
def data_date():
    date = driver.find_element(By.XPATH, '//*[@id="container"]/main/div[3]/div/div[1]/span/span').text
    date_edited = date[:-4]

    return date_edited

# 팀 이름을 가져오는 함수(1:홈팀, 2:어웨이팀)
def data_team_name(team_num):
    team_name = driver.find_element(By.XPATH, '//*[@id="container"]/main/div[3]/div/section[1]/div[1]/div['+str(team_num)+']/div[2]').text
    
    return team_name

# 쿼터 점수가져오는 함수(team num : 1(홈팀), 2(어웨이팀), qt : 2~7(1~4쿼터, 연장, 총 점수))
def data_score(team_num, qt):
    score = driver.find_element(By.XPATH, '//*[@id="container"]/main/div[3]/div/section[1]/div[2]/table/tbody/tr['+str(team_num)+']/td['+str(qt)+']').text
    
    return score

# Stat 가져오는 함수(team num : 1(홈팀), 2(어웨이팀), stat_num : 1~14(2점슛 ~ 3점슛 성공률))
def data_stat(team_num, stat_num):
    if team_num==1:
        stat = driver.find_element(By.XPATH, '//*[@id="container"]/main/div[3]/div/section[2]/section[4]/table/tbody/tr['+str(stat_num)+']/td[1]/span[2]').text
    elif team_num==2:
        stat = driver.find_element(By.XPATH, '//*[@id="container"]/main/div[3]/div/section[2]/section[4]/table/tbody/tr['+str(stat_num)+']/td[3]/span[1]').text
    else:
        pass
    
    return stat

In [ ]:

//*[@id="container"]/main/div[3]/div/section[1]/div[2]/table/thead/tr/th[3]

In [31]:
### 표를 만들기
### 크게 세 부분으로 추출
### 1. 경기 날짜, 팀 이름, 그 날의 경기 넘버, 홈/어웨이
### 2. 1~4 쿼터, 연장, 총 점수, Win/Lost
### 3. 경기 기록(2점, 3점 등)

def game_df(game_num):
    
    ## Part1. 경기날짜, 경기 번호, 팀이름, 홈/어웨이
    ## 홈팀의 인덱스는 1, 어웨이팀의 인덱스는 2로 지정하여 데이터 프레임 생성
    df = pd.DataFrame(columns=['Date', 'Game_num', 'Team', 'Home/Away'], index=[1,2]) # 컬럼과 인덱스 생성
    df['Date'] = data_date() # 경기 날짜 가져오는 함수 사용
    df['Game_num'] = game_num # game_num은 임의로 나중에 넣을 값(그 날의 경기 순서)
    
    for team_num in range(1,3): # 1=홈팀, 2=어웨이팀
        df['Team'][team_num] = data_team_name(team_num) # 행의 값=팀(홈/어웨이) 구분, 팀이름 가져오는 함수 사용
        if team_num == 1: # 홈/어웨이 넣어줄 것
            df['Home/Away'][team_num] = "Home"
        elif team_num == 2:
            df['Home/Away'][team_num] = "Away"
        else:
            pass
    
    ## Part2. 1Q~4Q, 연장, 총 점수 구하는 표
    score_name_list = [] # 점수 컬럼의 이름을 넣을 빈 리스트 생성
    score_home_list = [] # 홈팀의 점수 넣을 빈 리스트 생성
    score_away_list = [] # 어웨이팀의 점수 넣을 빈 리스트 생성
    
    for qt in range(2,8): # qt → 2~7 : 1~4/연장/총 점수
        score_name = driver.find_element(By.XPATH, '//*[@id="container"]/main/div[3]/div/section[1]/div[2]/table/thead/tr/th['+str(qt)+']').text
        score_name_list.append(score_name)
        
        for team_num in range(1,3):
            if team_num == 1:
                score_home = data_score(team_num, qt) # data_score 함수 활용
                score_home_list.append(score_home) # 빈리스트에 score_home 값 이어붙이기
            
            elif team_num ==2:
                score_away = data_score(team_num, qt) # data_score 함수 활용
                score_away_list.append(score_away) # 빈리스트에 score_away 값 이어붙이기
    
    score_df = pd.DataFrame(columns=score_name_list, index=[1,2], data=[score_home_list, score_away_list])
    # 스코어 데이터프레임 생성, 컬럼=각 점수 컬럼 이름, 인덱스=1,2, 데이터=score_home_list, score_away_list
    
    
    ## Part2-2 결합, 승리여부 넣어주기
    merged_df = pd.merge(df, score_df, left_index=True, right_index=True)
    merged_df['Win/Lose'] = 0 # 임의값 0으로 칼럼 생성
    
    if merged_df['TOTAL'][1] > merged_df['TOTAL'][2]: # 값 여부에 따라 win/lost 넣어주기
        merged_df['Win/Lose'][1] = "Won"
        merged_df['Win/Lose'][2] = "Lost"
    else:
        merged_df['Win/Lose'][1] = "Lost"
        merged_df['Win/Lose'][2] = "Won"
    
    
    ## Part3. 경기기록 표 구하기
    stat_columns_list = ["2PM", "3PM", "TR", "AST", "STL", "BLK", "FOUL", "FB", "TO", "PM", "GD", "FT%", "2P%", "3P%"]
    stat_home_list = []
    stat_away_list = []
    
    for stat_num in range(1, 15): # team_num → 1:홈팀 2:어웨이팀, stat_num → 1~14 : 2점슛 성공~3점슛 성공률
        for team_num in range(1,3):
            if team_num == 1:
                stat_home = data_stat(1, stat_num) # data_stat 함수 활용
                stat_home_list.append(stat_home) # stat_home 값 이어붙이기

            elif team_num == 2:
                stat_away = data_stat(2, stat_num) # data_stat 함수 활용
                stat_away_list.append(stat_away) # stat_away 값 이어붙이기
    
    stat_df = pd.DataFrame(columns=stat_columns_list, index=[1,2], data=[stat_home_list, stat_away_list])
    # stat_df 데이터프레임 생성, 칼럼, 인덱스=1,2, 인덱스 1의 값은 홈팀, 2의 값은 어웨이팀 데이터
    
    ## Part3-2 결합
    merged_df_2 = pd.merge(merged_df, stat_df, left_index=True, right_index=True) # 인덱스 기준으로 Part2-2, Part3 결합
    
    
    return merged_df_2

In [32]:
game_df(1)

/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Team'][team_num] = data_team_name(team_num) # 행의 값=팀(홈/어웨이) 구분, 팀이름 가져오는 함수 사용
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Home"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Away"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df['Win/Lose'][1] = "Won"

,Date,Game_num,Team,Home/Away,1Q,2Q,3Q,4Q,EQ,TOTAL,...,STL,BLK,FOUL,FB,TO,PM,GD,FT%,2P%,3P%
1,2006.10.20,1,대구오리온스,Home,18,30,23,21,0,92,...,11,2,21,4,17,28,1,70.0,55.4,20.0
2,2006.10.20,1,인천전자랜드,Away,26,17,30,14,0,87,...,9,6,27,11,24,20,1,64.0,52.4,40.9

In [52]:
### 하루동안 모든 경기 데이터 추출하는 함수
def day():
    
    click_match_box() # 경기 목록 클릭하기
    time.sleep(1) # 1초 휴식
    game_len = int(match_len()) # 그 날의 총 경기수 입력
    click_match_box()
    
    day_df = pd.DataFrame() # 하루의 모든 경기 데이터가 들어갈 빈 데이터 프레임 생성
    
    for game_num in range(1, (game_len+1)):
        click_match_box() # 경기 목록 클릭
        time.sleep(1)
        click_match(game_num) # 경기 목록 안의 경기 클릭
        time.sleep(1)
        one_game_df = game_df(game_num) # 데이터 추출함수 활용
        day_df = pd.concat([day_df, one_game_df]) # 데이터 프레임 이어 붙이기
    
    return day_df

In [53]:
day()

/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Team'][team_num] = data_team_name(team_num) # 행의 값=팀(홈/어웨이) 구분, 팀이름 가져오는 함수 사용
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Home"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Away"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df['Win/Lose'][1] = "Won"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Team'][team_num] = data_team_name(team_num) # 행의 값=팀(홈/어웨이) 구분, 팀이름 가져오는 함수 사용
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Home"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Away"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df['Win/Lose'][1] = "Won"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Team'][team_num] = data_team_name(team_num) # 행의 값=팀(홈/어웨이) 구분, 팀이름 가져오는 함수 사용
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Home"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Away"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df['Win/Lose'][1] = "Lost"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Team'][team_num] = data_team_name(team_num) # 행의 값=팀(홈/어웨이) 구분, 팀이름 가져오는 함수 사용
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Home"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Away"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df['Win/Lose'][1] = "Lost"

,Date,Game_num,Team,Home/Away,1Q,2Q,3Q,4Q,EQ,TOTAL,...,STL,BLK,FOUL,FB,TO,PM,GD,FT%,2P%,3P%
1,2006.10.21,1,창원LG,Home,20,30,11,18,0,79,...,10,4,24,6,14,16,0,52.6,51.4,36.7
2,2006.10.21,1,서울삼성,Away,16,27,15,12,0,70,...,4,4,18,4,19,17,2,68.8,54.3,38.9
1,2006.10.21,2,부산KTF,Home,30,17,26,19,0,92,...,7,3,22,7,9,21,2,89.3,65.0,26.3
2,2006.10.21,2,울산모비스,Away,22,21,11,24,0,78,...,4,2,24,4,12,20,2,66.7,54.3,27.3
1,2006.10.21,3,안양KT&G,Home,15,16,13,15,0,59,...,11,2,25,5,18,12,2,75.0,37.2,22.7
2,2006.10.21,3,원주동부,Away,16,21,17,19,0,73,...,10,5,20,3,15,16,3,88.2,44.7,42.1
1,2006.10.21,4,서울SK,Home,21,23,20,21,0,85,...,8,7,18,1,13,20,0,75.0,45.6,15.8
2,2006.10.21,4,전주KCC,Away,30,24,27,18,0,99,...,5,4,25,4,11,25,1,72.2,60.8,44.4

In [54]:
### 모든 날짜 반복하기
total_df = pd.DataFrame() # 빈 데이터프레임 생성
while True:
    day_df = day() # day_df 변수 = 하루의 모든 경기 데이터프레임
    time.sleep(1)
    total_df = pd.concat([total_df, day_df]) # 이어붙이기
    click_next_day() # 다음 날짜 클릭
    time.sleep(1)

/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Team'][team_num] = data_team_name(team_num) # 행의 값=팀(홈/어웨이) 구분, 팀이름 가져오는 함수 사용
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Home"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Away"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df['Win/Lose'][1] = "Won"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Team'][team_num] = data_team_name(team_num) # 행의 값=팀(홈/어웨이) 구분, 팀이름 가져오는 함수 사용
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Home"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Away"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df['Win/Lose'][1] = "Won"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Team'][team_num] = data_team_name(team_num) # 행의 값=팀(홈/어웨이) 구분, 팀이름 가져오는 함수 사용
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Home"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Away"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df['Win/Lose'][1] = "Lost"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Team'][team_num] = data_team_name(team_num) # 행의 값=팀(홈/어웨이) 구분, 팀이름 가져오는 함수 사용
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Home"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Away"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df['Win/Lose'][1] = "Lost"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Team'][team_num] = data_team_name(team_num) # 행의 값=팀(홈/어웨이) 구분, 팀이름 가져오는 함수 사용
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Home"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Away"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df['Win/Lose'][1] = "Lost"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Team'][team_num] = data_team_name(team_num) # 행의 값=팀(홈/어웨이) 구분, 팀이름 가져오는 함수 사용
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Home"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Away"

/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df['Win/Lose'][1] = "Lost"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Team'][team_num] = data_team_name(team_num) # 행의 값=팀(홈/어웨이) 구분, 팀이름 가져오는 함수 사용
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Home"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Away"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df['Win/Lose'][1] = "Won"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Team'][team_num] = data_team_name(team_num) # 행의 값=팀(홈/어웨이) 구분, 팀이름 가져오는 함수 사용
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Home"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Away"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df['Win/Lose'][1] = "Lost"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Team'][team_num] = data_team_name(team_num) # 행의 값=팀(홈/어웨이) 구분, 팀이름 가져오는 함수 사용
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Home"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Away"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df['Win/Lose'][1] = "Won"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Team'][team_num] = data_team_name(team_num) # 행의 값=팀(홈/어웨이) 구분, 팀이름 가져오는 함수 사용
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Home"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Away"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df['Win/Lose'][1] = "Lost"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Team'][team_num] = data_team_name(team_num) # 행의 값=팀(홈/어웨이) 구분, 팀이름 가져오는 함수 사용
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Home"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Away"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df['Win/Lose'][1] = "Won"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Team'][team_num] = data_team_name(team_num) # 행의 값=팀(홈/어웨이) 구분, 팀이름 가져오는 함수 사용
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Home"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Away"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df['Win/Lose'][1] = "Won"

/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Team'][team_num] = data_team_name(team_num) # 행의 값=팀(홈/어웨이) 구분, 팀이름 가져오는 함수 사용
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Home"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Home/Away'][team_num] = "Away"
/var/folders/vf/8b5vg3c94n1dx9pntt235qc80000gn/T/ipykernel_39348/1353978408.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df['Win/Lose'][1] = "Won"

KeyboardInterrupt:

In [55]:
total_df

,Date,Game_num,Team,Home/Away,1Q,2Q,3Q,4Q,EQ,TOTAL,...,STL,BLK,FOUL,FB,TO,PM,GD,FT%,2P%,3P%
1,2006.10.21,1,창원LG,Home,20,30,11,18,0,79,...,10,4,24,6,14,16,0,52.6,51.4,36.7
2,2006.10.21,1,서울삼성,Away,16,27,15,12,0,70,...,4,4,18,4,19,17,2,68.8,54.3,38.9
1,2006.10.21,2,부산KTF,Home,30,17,26,19,0,92,...,7,3,22,7,9,21,2,89.3,65.0,26.3
2,2006.10.21,2,울산모비스,Away,22,21,11,24,0,78,...,4,2,24,4,12,20,2,66.7,54.3,27.3
1,2006.10.21,3,안양KT&G,Home,15,16,13,15,0,59,...,11,2,25,5,18,12,2,75.0,37.2,22.7
2,2006.10.21,3,원주동부,Away,16,21,17,19,0,73,...,10,5,20,3,15,16,3,88.2,44.7,42.1
1,2006.10.21,4,서울SK,Home,21,23,20,21,0,85,...,8,7,18,1,13,20,0,75.0,45.6,15.8
2,2006.10.21,4,전주KCC,Away,30,24,27,18,0,99,...,5,4,25,4,11,25,1,72.2,60.8,44.4
1,2006.10.22,1,울산모비스,Home,21,19,13,16,0,69,...,5,2,25,3,12,14,4,71.4,55.0,19.2
2,2006.10.22,1,창원LG,Away,22,17,19,27,0,85,...,9,3,22,3,11,15,2,80.0,53.8,45.0
1,2006.10.22,2,원주동부,Home,17,19,22,11,0,69,...,4,6,21,2,19,15,2,75.0,50.0,26.1
2,2006.10.22,2,대구오리온스,Away,21,24,15,12,0,72,...,8,5,18,4,11,15,3,88.2,50.0,31.8
1,2006.10.22,3,인천전자랜드,Home,23,30,17,24,0,94,...,12,11,24,5,13,15,2,85.2,64.7,36.0
2,2006.10.22,3,서울SK,Away,24,23,32,12,0,91,...,7,1,23,7,20,21,3,78.6,58.1,40.0
1,2006.10.22,4,전주KCC,Home,23,13,18,16,0,70,...,2,1,22,3,10,12,3,50.0,55.2,32.3
2,2006.10.22,4,안양KT&G,Away,25,18,16,18,0,77,...,6,2,21,0,10,16,2,41.7,61.8,35.7
1,2006.10.24,1,부산KTF,Home,21,26,32,15,0,94,...,7,1,26,7,12,27,1,72.2,52.6,36.8
2,2006.10.24,1,대구오리온스,Away,25,19,28,20,0,92,...,4,6,20,2,17,22,1,73.3,63.0,21.1
1,2006.10.25,1,서울삼성,Home,30,20,25,11,3,89,...,8,5,21,7,14,25,0,68.4,56.9,31.6
2,2006.10.25,1,전주KCC,Away,27,19,16,24,6,92,...,8,6,24,5,13,21,2,68.8,53.3,39.3
1,2006.10.26,1,서울SK,Home,22,24,27,19,0,92,...,7,6,19,0,18,0,3,72.7,58.0,33.3
2,2006.10.26,1,울산모비스,Away,23,23,28,17,0,91,...,8,8,24,6,13,0,1,92.3,57.8,34.6
1,2006.10.27,1,원주동부,Home,20,15,27,23,0,85,...,7,5,16,5,7,23,1,88.9,58.3,38.9
2,2006.10.27,1,서울삼성,Away,25,21,18,18,0,82,...,4,4,17,2,11,18,1,100.0,58.3,46.2
1,2006.10.27,2,안양KT&G,Home,26,15,27,26,0,94,...,2,2,27,3,18,25,2,54.5,71.4,30.0
2,2006.10.27,2,창원LG,Away,33,27,24,27,0,111,...,11,0,19,7,8,23,4,75.0,63.8,42.3

In [99]:
total_df.to_excel('KBL데이터.xlsx')